spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tms?characterEncoding=utf8&useUnicode=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: root
      password: Yj6326076
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  quartz:
    scheduler-name: quartz_job
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  data:
    redis:
      host: 127.0.0.1
      database: 0
      jedis:
        pool:
          max-active: 8
          min-idle: 0
      connect-timeout: 1000
logging:
  file:
    name: build/tmsServer.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
  logback:
    rollingpolicy:
      file-name-pattern: build/tmsServer-%d{yyyy-MM-dd}.%i.log
      max-file-size: 20MB
      max-history: 10
      total-size-cap: 100MB
server:
  port: 8090

tmsServer:
  wzPath: config/wz